services:
  app:
    build:
      context: ./docker
      dockerfile: ./Dockerfile
    container_name: app
    working_dir: /var/www/html
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    ports:
      - "5432:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
  mariadb_data:
